// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID        pgtype.UUID
	Question  string
	Answer    string
	PackID    pgtype.UUID
	Rating    pgtype.Int4
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	LastWrong pgtype.Bool
}

type Log struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	PackID         pgtype.UUID
	RatingImproved pgtype.Int4
	RatingWorsen   pgtype.Int4
	CardsLearned   pgtype.Int4
	CardsMastered  pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Pack struct {
	ID        pgtype.UUID
	Name      string
	Category  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Subscription struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	PackID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserStat struct {
	UserID        pgtype.UUID
	Rating        pgtype.Int4
	PacksCreated  pgtype.Int4
	PacksMastered pgtype.Int4
}
